version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8110:80"
    volumes:
      - ./:/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
    image: gao922699/php7.2-fpm-for-laravel:latest
    volumes:
      - ./:/www
  node:
    image: node:8.0
    tty: true
    volumes:
      - ./:/www
    command: ["bash"]